[general]
import = [
    "~/.config/alacritty/themes/themes/breeze.toml"
]

[font]
normal = {
    family = "Cascadia Mono NF",
    style = "Regular"
}
size = 14.00

[cursor]
style = { blinking = "On" }

[bell]
animation = "Linear" # default: "Linear"
duration = 100 # in milliseconds, default: 0
color = "#ffffff" # default: "#ffffff"
command = "None" # default: "None"
