# Reload dunst config
#   dunstctl reload
#
# Restart dunst
#   killall dunst; dunst &
#
# Test dunst config changes
#   notify-send "Testing" "This is a test notification"

# Default config location: /etc/xdg/dunst/dunstrc

[global]
    ### Display ###

    # Which monitor should the notifications be displayed on.
    monitor = 0 # default: 0

    # Display notification on focused monitor.  Possible modes are:
    #   mouse: follow mouse pointer
    #   keyboard: follow window with keyboard focus
    #   none: don't follow anything
    #
    # "keyboard" needs a window manager that exports the
    # _NET_ACTIVE_WINDOW property.
    # This should be the case for almost all modern window managers.
    #
    # If this option is set to mouse or keyboard, the monitor option
    # will be ignored.
    follow = mouse # default: none

    ### Geometry ###

    # Defines width in pixels of frame around the notification window.
    # Set to 0 to disable.
    frame_width = 3 # default: 3

    # Defines color of the frame around the notification window.
    frame_color = "#c5c8c6" # default: "#aaaaaa"

    # Define a color for the separator.
    # possible values are:
    #  * auto: dunst tries to find a color fitting to the background;
    #  * foreground: use the same color as the foreground;
    #  * frame: use the same color as the frame;
    #  * anything else will be interpreted as a X color.
    separator_color = frame # default: frame

    ### Text ###

    font = Adwaita Mono 13 # default: Monospace 8

    ### Misc/Advanced ###

    # dmenu path.
    dmenu = rofi -dmenu -p dunst # default: /usr/bin/dmenu -p dunst:

    ### mouse

    # Defines list of actions for each mouse event
    # Possible values are:
    # * none: Don't do anything.
    # * do_action: Invoke the action determined by the action_name rule. If there is no
    #              such action, open the context menu.
    # * open_url: If the notification has exactly one url, open it. If there are multiple
    #             ones, open the context menu.
    # * close_current: Close current notification.
    # * remove_current: Remove current notification from history.
    # * close_all: Close all notifications.
    # * context: Open context menu for the notification.
    # * context_all: Open context menu for all notifications.
    # These values can be strung together for each mouse event, and
    # will be executed in sequence.
    mouse_left_click = close_current # default: close_current
    mouse_middle_click = do_action, close_current # default: do_action, close_current
    mouse_right_click = close_all # default: close_all

[urgency_low]
    # IMPORTANT: colors have to be defined in quotation marks.
    # Otherwise the "#" and following would be interpreted as a comment.
    background = "#263238" # default: "#222222"
    foreground = "#ffffff" # default: "#888888"
    timeout = 10 # default: 10
    # Icon for notifications with low urgency
    default_icon = dialog-information # default: dialog-information

[urgency_normal]
    background = "#1d1f21" # default: "#285577"
    foreground = "#ffffff" # default: "#ffffff"
    timeout = 10 # default: 10
    override_pause_level = 30 # default: 30
    # Icon for notifications with normal urgency
    default_icon = dialog-information # default: dialog-information

[urgency_critical]
    background = "#4a2525" # default: "#900000"
    foreground = "#ffffff" # default: "#ffffff"
    frame_color = "#c5c8c6" # default: "#ff0000"
    timeout = 0 # default: 0
    override_pause_level = 60 # default: 60
    # Icon for notifications with critical urgency
    default_icon = dialog-warning # default: dialog-warning
