[general]
; Set the day and night temperatures
temp-day=5700 ; 6500 is the default screen color temperature when Night Light is turned off
temp-night=4700

; Gradual transition between day and night
fade=1

; Set the brightness (0.1 to 1.0)
brightness-day=1.0
brightness-night=1.0

; Set the location-provider: 'geoclue2' or 'manual'
location-provider=manual

; Set the adjustment-method: 'wayland'
adjustment-method=wayland

[manual]
; Set the location's lat and lon
lat=13.0827
lon=80.2707
