[general]
; Set the day and night temperatures
temp-day=5700
temp-night=4500

; Gradual transition between day and night
fade=1

; Set the brightness (0.1 to 1.0)
brightness-day=1.0
brightness-night=0.8

; Set the location-provider: 'geoclue2' or 'manual'
location-provider=manual

; Set the adjustment-method: 'wayland'
adjustment-method=wayland

[manual]
; Set the location's lat and lon
lat=12.773677360541756
lon=80.01189030040908
